### ISSUE TITLE
remove current sidebar and add a modern one.

### ISSUE THREAD

**Issue by ShreyTanna29** [ShreyTanna29/curious.AI#27]
**Is your feature request related to a problem? Please describe.**
sidebar looks good but not one I would be proud of.

**Describe the solution you'd like**
add sidebar from shadcn compomnents
visit: https://ui.shadcn.com/docs/components/sidebar

**Describe alternatives you've considered**
N/A

**Check if applicable**
- [x] I have checked that this feature request does not exists on issues page.

**Additional context**

1. image of sidebar to be added.

![Screenshot from 2024-11-21 17-32-08](https://github.com/user-attachments/assets/d73582a9-c085-4455-a397-cdbba6794bd7)

**Comment by sarahagib** [comment]
Hi, my name is Sarah and I'm an engineering student looking for a good first issue. I would like to work on this if it's not assigned to anyone yet?

**Comment by ShreyTanna29** [comment]
@sarahagib go ahead, if you need any help then ask me.

**Comment by sarahagib** [comment]
Hi, I'm so sorry to do this but something has come up and I won't be able to work on this issue any time soon. I apologize.

**Comment by ShreyTanna29** [comment]
@sarahagib no issues
