### ISSUE TITLE
change color of close button in sidebar in light mode in mobile view.

### ISSUE THREAD

**Issue by ShreyTanna29** [ShreyTanna29/curious.AI#36]
**Describe the bug**
when on mobile view, close button of sidebar is not visible in light mode but it is showing in dark mode 

**To Reproduce**
1. Go to mobile view of website (using mobile or just inspect the site and activate mobile view)
2. Click on top left menu
3. check top right corner, close button will not be visible if you have selected light mode in settings.

**Expected behavior**
close button's color should be black in light mode.

**Screenshots**
![Screenshot from 2024-11-25 12-26-55](https://github.com/user-attachments/assets/4780e155-74d0-4b67-8732-22033e4276df)
![Screenshot from 2024-11-25 12-26-44](https://github.com/user-attachments/assets/c58c785f-92e6-40db-bfec-9c6bd0b9025c)

**check if appllicable**
- [x] I have checked that this bug does not exists on issues page

**Additional context**
N/A

**Comment by ahmedhalac** [comment]
Hi @ShreyTanna29. Can i work on this?

**Comment by ShreyTanna29** [comment]
@ahmedhalac go ahead, if you need any help then feel free to ask.

**Comment by ShreyTanna29** [comment]
hey @ahmedhalac  , are you working on it ? any updates ?

**Comment by ahmedhalac** [comment]
Hi @ShreyTanna29. Sorry for the late reply. 
I have an issue with getting the Gemini API key. It looks like my country isn't supported from Google AI studio.
That's why I cannot set Gemini Api key in .env

**Comment by ShreyTanna29** [comment]
@ahmedhalac , no issues, your changes are merged, congratulations.
