### ISSUE TITLE
align buttons column wise i settings

### ISSUE THREAD

**Issue by ShreyTanna29** [ShreyTanna29/curious.AI#40]
**Is your feature request related to a problem? Please describe.**
those buttons in settings page doesnt look good.

**Describe the solution you'd like**
align them below one another i.e. align manage account button exactly below themes button and logout button beside manage account button, right now logout is beside manage account button but manage account button is not properly below themes button.

**Describe alternatives you've considered**
N/A

**Check if applicable**
- [x] I have checked that this feature request does not exists on issues page.

**Additional context**
am talking about this buttons
![Screenshot from 2024-11-26 19-22-21](https://github.com/user-attachments/assets/6c38e63b-5c5b-4e35-9b75-13cb8d8696b4)

**Comment by rohitmore07** [comment]
Hey @ShreyTanna29 I'm very keen to work on this issue. I would be really happy if you could assign this issue to me.

**Comment by ShreyTanna29** [comment]
@rohitmore07 go ahead, if you need any help, then feel free to ask.

**Comment by rohitmore07** [comment]
Sure.

**Comment by ShreyTanna29** [comment]
hey @rohitmore07  , are you working on it ? any updates ?

**Comment by rohitmore07** [comment]
Yeah, I'm working on it!

**Comment by ShreyTanna29** [comment]
hey @rohitmore07  

any updates regarding this ?? please let me know if you need any help.

**Comment by rohitmore07** [comment]
![image](https://github.com/user-attachments/assets/64fc8864-6f8e-49b3-9bdf-cf803f94058b)

**Comment by ShreyTanna29** [comment]
@rohitmore07 you need api keys for clerk auth, just go there website and create a project and get api keys and paste in your .env file, just look at .env.example, you need all that keys in your .env, dont worry they are free and easy to get, still if you get stuck somewhere, just ask me, also you will need a postgres DB, if you know how to do it locally that's best or else got to supabase or any other postgres full DB instance provider,  and get DB url from there, ask me if you need any further help.

**Comment by rohitmore07** [comment]
Added PR.

**Comment by ShreyTanna29** [comment]
@rohitmore07 your PR got merged, congrats !

**Comment by ShreyTanna29** [comment]
@rohitmore07 I guess you can also solve this one #48
