### ISSUE TITLE
create a nice footer for landing page.

### ISSUE THREAD

**Issue by ShreyTanna29** [ShreyTanna29/curious.AI#66]
**Is your feature request related to a problem? Please describe.**
right now there is no footer in landing page(kind of)

**Describe the solution you'd like**
a simple and responsive footer.

**Describe alternatives you've considered**
N/A

**Check if applicable**
- [x] I have checked that this feature request does not exists on issues page.

**Additional context**
N/A

**Comment by Akhilesh1326** [comment]
Hey I would like to contribute to this issue, if it's not assigned yet, then please assign it to me, I'd be glad to resolve it, and please give a simple explanation of what enhancement is needed.

**Comment by ShreyTanna29** [comment]
@Akhilesh1326 go ahead, just create a nice footer for the landing page, here is a sample image 

![Screenshot from 2024-12-14 20-02-22](https://github.com/user-attachments/assets/ee7da5ed-7488-481f-9922-6594614d17a7)


no need of social media icons ( as curious ai doesn't have any right now), and instead of privacy policy and all that stuff, you can put our image generation , code generation and chat page links.And can also include login and signup links as well, you can add extra changes or design as you like it, creativity is always well-comed by me. Let me know if you need any further help.

**Comment by Akhilesh1326** [comment]
Hey, i was opening the site, but it's saying that the clerk publishable key is missing, even though in .env file it's there, there anything I need to do before doing npm run dev, apologise if it's an inconvenience for you, I am still learning and new to open source contribution.

**Comment by ShreyTanna29** [comment]
Hey @Akhilesh1326 ,

You will need both publishable and secret key from clerk, and make sure to not to use publishable key from .env.example and get yours both keys from clerk auth by creating an project/app on there website. Make sure you have all the keys suggested in .env.example. check this and if this issue continues then send me screenshot of the error and ask for any required help without any hesitation.

**Comment by ShreyTanna29** [comment]
@Akhilesh1326  congrats, your PR has been merged.
