### ISSUE TITLE
fix: disable surprise me button when image is being generated.

### ISSUE THREAD

**Issue by ShreyTanna29** [ShreyTanna29/curious.AI#67]
**Describe the bug**
surprise me button is not disabled when image is being generated

**To Reproduce**
1. Go to image page
2. write prompt and click on create
3. check that surprise me button is not disabled.
4. if clicked on surpirse me button when image is being generated the input disappear as form is being cleared after generating an image

**Expected behavior**
suprise me button should be disabled when image is being generated.

**Screenshots**
N/A

**check if appllicable**
- [x] I have checked that this bug does not exists on issues page

**Additional context**
N/A

**Comment by goutham03062001** [comment]
Hi @ShreyTanna29 is this issue still open? I would like to contribute on this bug

**Comment by ShreyTanna29** [comment]
@goutham03062001 yes, go ahead 👍.
